POST http://localhost:3000/email
content-type: application/json

{
  "subject": "Assunto do Email",
  "body": "texto ou html do email",
  "contacts": [
    {
      "name": "Diogo",
      "email":"diogosilvaoficial@gmail.com"
    },
    {
      "name": "Diogo",
      "email":"diogosilvaoficial@gmail.com"
    }
  ]
}

###
GET http://localhost:3000/email
content-type: application/json